### PR TITLE
Diagonal strafing

### PR DESCRIPTION
**Pull request by arihant2math**
TODO:
- [ ] Add CalcMotorTickCounts2D method
- [x] Fix AllMotorPidControl

### CODE REVIEW

**Comment by moogloof** [comment]
Does not build bc of changes to `build.dependencies.gradle`

**Comment by moogloof** [comment]
Changed to `allMotorPID` will not work functionally. I will write up something describing that and the code, so this branch will remain unmerged until then. Keep this pull open

**Review by albonec — APPROVED** [review]
lgtm

**Comment by moogloof** [comment]
test on saturday, we'll merge after changes

**Comment by arihant2math** [comment]
Merged into vison, merge will happen at #9

**Pull request closed without merging**
